"""empty message

Revision ID: 048ede4c3286
Revises: b4d52573338e
Create Date: 2022-12-07 09:49:52.982261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048ede4c3286'
down_revision = 'b4d52573338e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
