"""empty message

Revision ID: 1057642623a0
Revises: bb0895fad182
Create Date: 2022-12-09 10:35:00.676831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1057642623a0'
down_revision = 'bb0895fad182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=50), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('instagram', sa.String(length=50), nullable=True),
    sa.Column('twitter', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_about'))
    )
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=60), nullable=True),
    sa.Column('body', sa.String(length=20), nullable=True),
    sa.Column('recepients', sa.JSON(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter'))
    )
    op.create_table('newsletter_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_emails'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_emails')
    op.drop_table('newsletter')
    op.drop_table('about')
    # ### end Alembic commands ###
