"""empty message

Revision ID: 345226569eaa
Revises: 4f95bd7a7c78
Create Date: 2022-12-08 23:06:52.620691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345226569eaa'
down_revision = '4f95bd7a7c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
