"""empty message

Revision ID: 5c0ac953a624
Revises: dc359b0bd337
Create Date: 2022-12-10 23:10:26.256186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c0ac953a624'
down_revision = 'dc359b0bd337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tickets_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_items_events_id_event'), 'event', ['events_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_items_tickets_id_tickets'), 'tickets', ['tickets_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_items_tickets_id_tickets'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_items_events_id_event'), type_='foreignkey')
        batch_op.drop_column('tickets_id')
        batch_op.drop_column('events_id')

    # ### end Alembic commands ###
