"""empty message

Revision ID: 5d863271ca3d
Revises: 682372a008f4
Create Date: 2022-12-17 15:20:09.804323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d863271ca3d'
down_revision = '682372a008f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qrcode', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('qr_id', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('qr_id')
        batch_op.drop_column('qrcode')

    # ### end Alembic commands ###
