"""empty message

Revision ID: 68adcce2659e
Revises: fc7b2899b714
Create Date: 2022-12-10 17:03:35.184439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68adcce2659e'
down_revision = 'fc7b2899b714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_reference', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('cart_reference')

    # ### end Alembic commands ###
