"""empty message

Revision ID: 77b5b5891ebc
Revises: bf75a9a2c5f0
Create Date: 2022-12-07 00:47:54.645401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b5b5891ebc'
down_revision = 'bf75a9a2c5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image1', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image2', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')
        batch_op.drop_column('image1')

    # ### end Alembic commands ###
