"""empty message

Revision ID: b623039bc6e1
Revises: cd637e88257e
Create Date: 2022-12-10 21:02:18.872758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b623039bc6e1'
down_revision = 'cd637e88257e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verification', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')
        batch_op.drop_column('verification')
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
