"""empty message

Revision ID: bf75a9a2c5f0
Revises: a76e2b056848
Create Date: 2022-12-07 00:02:41.052720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf75a9a2c5f0'
down_revision = 'a76e2b056848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_ticket_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket'))
    )
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.drop_index('ix_about_email')

    op.drop_table('about')
    op.drop_table('blocks')
    op.drop_table('price')
    op.drop_table('appearances')
    op.drop_table('faq')
    op.drop_table('teams')
    op.drop_table('testimonial')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=140), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('faceboook', sa.VARCHAR(length=140), nullable=True),
    sa.Column('instagram', sa.INTEGER(), nullable=True),
    sa.Column('twitter', sa.INTEGER(), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=140), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('appearances',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('subtitle_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('paragraph_color', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_font', sa.VARCHAR(length=64), nullable=True),
    sa.Column('subtitle_font', sa.VARCHAR(length=64), nullable=True),
    sa.Column('paragraph_font', sa.VARCHAR(length=64), nullable=True),
    sa.Column('title_size', sa.INTEGER(), nullable=True),
    sa.Column('subtitle_size', sa.INTEGER(), nullable=True),
    sa.Column('paragraph_size', sa.INTEGER(), nullable=True),
    sa.Column('bootstrap_class1', sa.VARCHAR(length=64), nullable=True),
    sa.Column('bootstrap_class2', sa.VARCHAR(length=64), nullable=True),
    sa.Column('bootstrap_class3', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('amount', sa.TEXT(), nullable=False),
    sa.Column('features', sa.TEXT(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('block_type', sa.VARCHAR(), nullable=True),
    sa.Column('appearance_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('about',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('atext', sa.TEXT(), nullable=False),
    sa.Column('image', sa.VARCHAR(length=64), nullable=True),
    sa.Column('about_image', sa.VARCHAR(length=64), nullable=True),
    sa.Column('location', sa.VARCHAR(length=140), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('contact_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('about_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('feature_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('feature_paragraph', sa.TEXT(), nullable=True),
    sa.Column('faq_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('faq_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('faq_paragraph', sa.VARCHAR(length=140), nullable=True),
    sa.Column('testimonial_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('testimonial_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('testimonial_paragraph', sa.VARCHAR(length=140), nullable=True),
    sa.Column('team_title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('team_subtitle', sa.VARCHAR(length=140), nullable=True),
    sa.Column('team_paragraph', sa.VARCHAR(length=140), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=64), nullable=True),
    sa.Column('carousel_image_1', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.create_index('ix_about_email', ['email'], unique=False)

    op.drop_table('ticket')
    op.drop_table('event')
    # ### end Alembic commands ###
