"""empty message

Revision ID: cd637e88257e
Revises: 68adcce2659e
Create Date: 2022-12-10 18:07:50.836359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd637e88257e'
down_revision = '68adcce2659e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.String(length=200), nullable=True))
        batch_op.drop_column('cart_reference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_reference', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('reference')

    # ### end Alembic commands ###
