"""empty message

Revision ID: dc359b0bd337
Revises: 9cbacc6f013d
Create Date: 2022-12-10 23:07:04.612134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc359b0bd337'
down_revision = '9cbacc6f013d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('cart_id', name=op.f('pk_carts'))
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('image1', sa.String(length=100), nullable=True),
    sa.Column('image2', sa.String(length=100), nullable=True),
    sa.Column('image3', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('eventtags', sa.String(length=200), nullable=True),
    sa.Column('baseprice', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_table('newsletter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=60), nullable=True),
    sa.Column('body', sa.String(length=20), nullable=True),
    sa.Column('recepients', sa.JSON(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter'))
    )
    op.create_table('newsletter_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_newsletter_emails'))
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_articles_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles'))
    )
    op.create_table('items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.cart_id'], name=op.f('fk_items_cart_id_carts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_items_user_id_users')),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_items'))
    )
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('day', sa.String(), nullable=True),
    sa.Column('features', sa.String(length=255), nullable=True),
    sa.Column('image', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_tickets_event_id_event')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets'))
    )
    op.drop_table('teams')
    op.drop_table('testimonial')
    op.drop_table('faq')
    op.drop_table('price')
    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('instagram', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('twitter', sa.String(length=50), nullable=True))
        batch_op.drop_index('ix_about_email')
        batch_op.drop_column('about_image')
        batch_op.drop_column('location')
        batch_op.drop_column('faq_paragraph')
        batch_op.drop_column('text')
        batch_op.drop_column('carousel_image_1')
        batch_op.drop_column('testimonial_subtitle')
        batch_op.drop_column('subtitle')
        batch_op.drop_column('about_subtitle')
        batch_op.drop_column('faq_subtitle')
        batch_op.drop_column('team_subtitle')
        batch_op.drop_column('title')
        batch_op.drop_column('logo')
        batch_op.drop_column('faq_title')
        batch_op.drop_column('team_paragraph')
        batch_op.drop_column('feature_subtitle')
        batch_op.drop_column('image')
        batch_op.drop_column('testimonial_paragraph')
        batch_op.drop_column('testimonial_title')
        batch_op.drop_column('contact_subtitle')
        batch_op.drop_column('atext')
        batch_op.drop_column('feature_paragraph')
        batch_op.drop_column('team_title')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('role', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('verification', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=100), nullable=True))

    with op.batch_alter_table('web_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wtext', sa.Text(), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('web_feature', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.drop_column('wtext')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('verification_code')
        batch_op.drop_column('verification')
        batch_op.drop_column('role')
        batch_op.drop_column('name')

    with op.batch_alter_table('about', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_title', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('feature_paragraph', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('atext', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('contact_subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('testimonial_title', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('testimonial_paragraph', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('feature_subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('team_paragraph', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('faq_title', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('logo', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('team_subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('faq_subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('about_subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('testimonial_subtitle', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('carousel_image_1', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('text', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('faq_paragraph', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=140), nullable=False))
        batch_op.add_column(sa.Column('about_image', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_about_email', ['email'], unique=False)
        batch_op.drop_column('twitter')
        batch_op.drop_column('instagram')
        batch_op.drop_column('address')
        batch_op.drop_column('name')

    op.create_table('price',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=False),
    sa.Column('amount', sa.TEXT(), nullable=False),
    sa.Column('features', sa.TEXT(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_price')
    )
    op.create_table('faq',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.VARCHAR(length=140), nullable=False),
    sa.Column('answer', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_faq')
    )
    op.create_table('testimonial',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('text', sa.VARCHAR(length=140), nullable=True),
    sa.Column('rating', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_testimonial')
    )
    op.create_table('teams',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('faceboook', sa.VARCHAR(length=140), nullable=True),
    sa.Column('instagram', sa.INTEGER(), nullable=True),
    sa.Column('twitter', sa.INTEGER(), nullable=True),
    sa.Column('picture', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_teams')
    )
    op.drop_table('tickets')
    op.drop_table('items')
    op.drop_table('articles')
    op.drop_table('newsletter_emails')
    op.drop_table('newsletter')
    op.drop_table('event')
    op.drop_table('carts')
    # ### end Alembic commands ###
